// Cloudflare Pages middleware: content negotiation for markdown.
//
// When a request sends `Accept: text/markdown`, serve the pre-built `.md`
// variant of the page (generated by Hugo's MARKDOWN output format) instead of
// HTML. Browsers and anything not explicitly asking for markdown get HTML,
// unchanged.
//
// Runs on every request. See hugo.toml [outputFormats.MARKDOWN]. The
// `Vary: Accept` header is set for all routes in static/_headers so caches
// don't cross-serve the HTML and markdown representations.

export async function onRequest(context) {
  const { request, next } = context;

  const accepts = request.headers.get("Accept") || "";
  // Require markdown to be explicitly acceptable — a bare `*/*` keeps HTML.
  if (!/text\/markdown/i.test(accepts)) {
    return next();
  }

  const url = new URL(request.url);
  const path = url.pathname;

  let mdPath;
  if (path.endsWith("/")) {
    mdPath = path + "index.md";
  } else if (!/\.[a-z0-9]+$/i.test(path)) {
    // Extensionless page URL (e.g. /blog/post) -> /blog/post/index.md
    mdPath = path + "/index.md";
  } else {
    // Already a concrete file (assets, rss.xml, sitemap.xml, agents.md, …).
    // Not a negotiable page — serve it as-is.
    return next();
  }

  const mdUrl = new URL(url);
  mdUrl.pathname = mdPath;

  // Fetch the static .md asset that Hugo built for this page.
  const res = await next(new Request(mdUrl, request));

  // No markdown variant for this path (e.g. 404) -> fall back to HTML.
  if (!res.ok) {
    return next();
  }

  const body = await res.text();

  const headers = new Headers(res.headers);
  headers.set("Content-Type", "text/markdown; charset=utf-8");
  headers.set("Vary", "Accept");
  // Byte length may differ from the string length; let the runtime recompute.
  headers.delete("Content-Length");
  const tokens = estimateTokens(body);
  if (tokens != null) {
    headers.set("x-markdown-tokens", String(tokens));
  }

  return new Response(body, { status: 200, headers });
}

// Rough token estimate (~4 chars/token for English) — best-effort, no
// tokenizer runs at the edge. Computed off the served bytes so there's no
// build-time manifest to drift.
function estimateTokens(text) {
  if (!text) return null;
  return Math.ceil(text.length / 4);
}
